go:
  # Whenever the Go version is updated here, .circle/config.yml should also
  # be updated.
  version: 1.14

repository:
  path: github.com/slashdevops/aws_cloudwatch_exporter

build:
  flags: -mod=mod -a -tags 'netgo static_build'
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}

tarball:
  files:
    - README.md
    - CHANGELOG.md
    - LICENSE
    - NOTICE
    - docs
    - server.yaml
    - credentials.yaml

crossbuild:
  platforms:
    - linux/amd64
    - linux/386
    - linux/arm
    - linux/arm64
    - darwin/amd64
    - darwin/386
    - windows/amd64
    - windows/386
