name: Release workflow

on:
  push:
    tags:
      - v[012].[0-9]+.[0-9]+ # https://help.github.com/es/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

env:
  DOCKER_HUB_REPO: "docker.io/slashdevops"
  DOCKER_BUILD_ARCHS: "amd64"

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22.4
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install promu
        run: make promu

      - name: Build and Test Linux Platform Only
        run: make

      - name: Check code modifications
        run: git diff --exit-code

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22.4
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install promu
        run: make promu

      - name: Build Cross-Platform
        run: promu crossbuild -v

      - name: List Workspace Files
        run: ls -la .

      - name: List .build Files
        run: ls -la .build

      - name: Upload .build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: .build
          path: .build

  publish_docker_images:
    name: Publish Docker Images
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22.4
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install promu
        run: make promu

      - name: Show Package Information
        run: promu info

      - name: Docker Version
        run: docker version

      - name: Download .build artifacts from Build Step
        uses: actions/download-artifact@v4
        with:
          name: .build
          path: .build

      - name: Assign Execution Permission to Binaries
        run: chmod -R +x .build/*/*

      - name: List Workspace Files
        run: ls -la .

      - name: List .build Files
        run: ls -la .build

      - name: Set Env Var RELEASE_VERSION
        run: |
          echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Show RELEASE_VERSION
        run: echo $RELEASE_VERSION

      - name: Build Docker Images
        run: make docker DOCKER_IMAGE_TAG=$RELEASE_VERSION DOCKER_REPO=$DOCKER_HUB_REPO DOCKER_ARCHS=$DOCKER_BUILD_ARCHS

      - name: Docker Tag Images Latest
        run: make docker-tag-latest DOCKER_IMAGE_TAG=$RELEASE_VERSION DOCKER_REPO=$DOCKER_HUB_REPO DOCKER_ARCHS=$DOCKER_BUILD_ARCHS

      - name: Show Local Docker Images
        run: docker images

      - name: Loging in Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Publish Images in Docker Hub
        run: make docker-publish DOCKER_IMAGE_TAG=$RELEASE_VERSION DOCKER_REPO=$DOCKER_HUB_REPO DOCKER_ARCHS=$DOCKER_BUILD_ARCHS

      - name: Publish Manifest in Docker Hub
        run: make docker-manifest DOCKER_IMAGE_TAG=$RELEASE_VERSION DOCKER_REPO=$DOCKER_HUB_REPO DOCKER_ARCHS=$DOCKER_BUILD_ARCHS

  create_release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_github_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          # body: |
          #   See the file: CHANGELOG.md
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  publish_tarballs:
    name: Publish Tarballs
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22.4
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install promu
        run: make promu

      - name: Show Package Information
        run: promu info

      - name: Download .build artifacts from Build Step
        uses: actions/download-artifact@v4
        with:
          name: .build
          path: .build

      - name: Assign Execution Permission to Binaries
        run: chmod -R +x .build/*/*

      - name: List Workspace Files
        run: ls -la .

      - name: List .build Files
        run: ls -la .build

      - name: Build Tarballs Files
        run: promu crossbuild tarballs

      - name: Checksum Tarballs Files
        run: promu checksum .tarballs

      - name: Release Tarballs Files
        run: promu release -v .tarballs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts to Github
        uses: actions/upload-artifact@v4
        with:
          name: releases
          path: .tarballs
